### ISSUE TITLE
Add udev rules for managing usb serial ports

### ISSUE THREAD

**Issue by agutier4** [pongrobot/pongrobot-vision#2]
Create a set of .rules files to clean up the USB port system. Rules should distinguish between the two 32U4 boards but do not need to account for the VESCs. The Realsesnse has its own rules and can be ignored

**Comment by chrisdalke** [comment]
See https://www.sparkfun.com/news/2332 for reference on udev rules setup.

**Comment by agutier4** [comment]
New board definitions are added under pongrobot/pongrobot_arduino_sketches [b6481d8](https://github.com/pongrobot/pongrobot_arduino_sketches/tree/master/hardware)
